---
title: "Week3"
author: "Tiabet"
date: "2023-09-19"
output: html_document
---

간단한 함수들 사용
```{r}
print(Sys.Date())
print(mean(c(2,4,5)))
```

함수 정의

```{r}
boring_function <- function(x){
 x+3
}
#디폴트 선언
remainder <- function(num=7,divisor=3){
  num %% divisor
}
print(boring_function(4))
remainder(10,4)
remainder(divisor = 100, num = 123124)

evaluate<-function(func,dat){
  func(dat)
}

evaluate(sd,c(3,6,2,9))
#함수 안에서도 정의 가능능
evaluate(function(x){x[length(x)]},c(3,6,7,8))

```
paste 함수 사용
```{r}
telegram<-function(...){
  paste("START", ..., "STOP", sep = ' ')
}
telegram("Message")
```

실습 예제 1
포아송 분포에서는 input값의 mean이 MLE과 비슷함.
```{r}
load("./data/e100.RData")
#max(e100)
e99 = e100[-which.max(e100)]
e99
barplot(table(e99), space = 0.8, col = "chartreuse4")

library(vcd)
gf1 = goodfit(e99, "poisson")
rootogram(gf1, xlab = "x-bar", rect_gp = gpar(fill = "chartreuse4"))

table(e100)
table(rpois(100, 3))

loglikelihood = function(lambda, data = e100){
  sum(log(dpois(data, lambda)))
}
lambdas = seq(0.05, 0.95, length = 100)
loglik = vapply(lambdas, loglikelihood, numeric(1))

plot(lambdas, loglik, type = 'l', col = "red", ylab = "", lwd = 2,
     xlab = expression(lambda))

m0 = mean(e100)

abline(v = m0, col = "blue", lwd = 2) #v는 수직선
abline(h = loglikelihood(m0), col = "purple", lwd = 2) #h는 수평선

#간단히 할 수 있는 goodfit 함수
gf  =  goodfit(e100, "poisson")
gf$par==m0 #둘이 동일함
table(rpois(100, 0.55))
```
실습 예제 2
```{r}
cb  =  c(rep(0, 110), rep(1, 10))
table(cb)
probs  =  seq(0, 0.3, by = 0.005)
likelihood = dbinom(sum(cb), prob = probs, size = length(cb))
plot(probs, likelihood, pch = 16, xlab = "probability of success",
       ylab = "likelihood", cex=0.6)

which.max(likelihood)

```