---
title: "Week13"
author: "Tiabet"
date: "2023-11-30"
output: html_document
---
## 이미지 데이터
### readImage로 읽은 다음에 display로 띄운다.
### 흑백이건 컬러건 데이터가 1에 가까우면 색이 많이 들어갔다는 것을 의미한다.
### 흑백에선 1에 가까울수록 흰색이다.

```{r}
library(EBImage)

imagefile = system.file("images", "mosquito.png", package = "MSMB")
mosq = readImage(imagefile)

EBImage::display(mosq)

EBImage::display(mosq, method = "raster")
text(x = 85, y = 800, label = "A mosquito", adj = 0, col = "orange", cex = 1.5)

imagefile = system.file("images", "hiv.png", package = "MSMB")
hivc = readImage(imagefile)
EBImage::display(hivc)

nuc = readImage(system.file("images", "nuclei.tif", package = "EBImage"))
EBImage::display(1 - nuc, method = "raster", all = TRUE)

EBImage::display(nuc, method = "raster", frame = 2)
```
```{r}
class(mosq)
dim(mosq)
hist(mosq,200)
imageData(mosq)[1:3, 1:6]
mosq
hivc
hivc[1000:1100, 500:600, 1]
```

## 이미지 저장하기
```{r}
writeImage(hivc, "hivc.jpeg", quality = 85)
```

## 이미지 조작하기
```{r}
mosqinv = normalize(-mosq)
EBImage::display(mosqinv)

mosqcont = mosq * 3
EBImage::display(mosqcont)

mosqexp = mosq ^ (1/3)
EBImage::display(mosqexp)

mosqcrop   = mosq[100:438, 112:550]
mosqthresh = mosq > 0.5
mosqtransp = transpose(mosq)

EBImage::display(mosqcrop)
EBImage::display(mosqthresh)
```


```{r}
imagefiles = system.file("images", c("image-DAPI.tif", "image-FITC.tif", "image-Cy3.tif"), package = "MSMB")
cells = readImage(imagefiles)
cells

apply(cells, 3, range)

cells[,,1]   = 32 * cells[,,1]
cells[,,2:3] = 16 * cells[,,2:3]
apply(cells, 3, range)

w = makeBrush(size = 51, shape = "gaussian", sigma = 7)
nucSmooth = filter2(getFrame(cells, 1), w)
cellsSmooth = Image(dim = dim(cells))
sigma = c(1, 3, 3)
for(i in seq_along(sigma))
  cellsSmooth[,,i] = filter2( cells[,,i],
         filter = makeBrush(size = 51, shape = "gaussian",
                            sigma = sigma[i]) )
EBImage::display(cellsSmooth, method = "raster", all = TRUE)
```

```{r}
py = seq(-1, +1, length.out = dim(cellsSmooth)[1])
px = seq(-1, +1, length.out = dim(cellsSmooth)[2])
illuminationGradient = Image(
     outer(py, px, function(x, y) exp(-(x^2+y^2))))
nucBadlyIlluminated = cellsSmooth[,,1] * illuminationGradient

disc = makeBrush(21, "disc")
disc = disc / sum(disc)
localBackground = filter2(nucBadlyIlluminated, disc)
offset = 0.02
nucBadThresh = (nucBadlyIlluminated - localBackground > offset)

nucThresh = (cellsSmooth[,,1] - filter2(cellsSmooth[,,1], disc) > offset)

nucOpened = EBImage::opening(nucThresh,
                  kern = makeBrush(5, shape = "disc"))
EBImage::display(nucOpened)

nucSeed = bwlabel(nucOpened)
table(nucSeed)
EBImage::display(colorLabels(nucSeed))
nucMask = cellsSmooth[,,1] - filter2(cellsSmooth[,,1], disc) > 0
nucMask = fillHull(nucMask)
nuclei = propagate(cellsSmooth[,,1], nucSeed, mask = nucMask)
EBImage::display(colorLabels(nuclei))
```

```{r}
zeros        = Image(dim = dim(nuclei))
voronoiExamp = propagate(seeds = nuclei, x = zeros, lambda = 100)
voronoiPaint = paintObjects(voronoiExamp, 1 - nucOpened)
EBImage::display(voronoiPaint)

hist(log(cellsSmooth[,,3]) )
hist(log(cellsSmooth[,,3]), xlim = -c(3.6, 3.1), breaks = 300)

library("genefilter")
bgPars = function(x) {
  x    = log(x)
  loc  = half.range.mode( x )
  left = (x - loc)[ x < loc ]
  wid  = sqrt( mean(left^2) )
  c(loc = loc, wid = wid, thr = loc + 6*wid)
}
cellBg = apply(cellsSmooth, MARGIN = 3, FUN = bgPars)
cellBg
hist(log(cellsSmooth[,,3]), xlim = -c(3.6, 3.1), breaks = 300)
abline(v = cellBg[c("loc", "thr"), 3], col = c("brown", "red"))
cytoplasmMask = (cellsSmooth[,,2] > exp(cellBg["thr", 2])) |
       nuclei | (cellsSmooth[,,3] > exp(cellBg["thr", 3]))
EBImage::display(cytoplasmMask, method = "raster")

cellbodies = propagate(x = cellsSmooth[,,3], seeds = nuclei,
                       lambda = 1.0e-2, mask = cytoplasmMask)
EBImage::display(colorLabels(cellbodies), method = "raster")
```

```{r}
meanNucInt       = tapply(cells[,,1], nuclei, mean)
meanActIntInNuc  = tapply(cells[,,3], nuclei, mean)
meanActIntInCell = tapply(cells[,,3], cellbodies, mean)
library("GGally")
library("dplyr")
ggpairs(tibble(meanNucInt, meanActIntInNuc, meanActIntInCell))

F1 = computeFeatures(nuclei,     cells[,,1], xname = "nuc",
                                             refnames = "nuc")
F2 = computeFeatures(cellbodies, cells[,,2], xname = "cell",
                                             refnames = "tub")
F3 = computeFeatures(cellbodies, cells[,,3], xname = "cell",
                                             refnames = "act")
dim(F1)
F1[1:3, 1:5]
```

```{r}
library("readr")
library("dplyr")
cellclasses = c("T_cells", "Tumor", "DCs", "other_cells")
brcalymphnode = lapply(cellclasses, function(k) {
    read_csv(file.path(".", "data",
             sprintf("99_4525D-%s.txt", k))) |>
    transmute(x = globalX,
              y = globalY,
              class = k)
}) |> bind_rows() |> mutate(class = factor(class))
brcalymphnode
table(brcalymphnode$class)
ggplot(filter(brcalymphnode, class %in% c("T_cells", "Tumor")),
   aes(x = x, y = y, col = class)) + geom_point(shape = ".") +
   facet_grid( . ~ class) + guides(col = "none")
library("spatstat")
ln = with(brcalymphnode,
  ppp(x = x, y = y, marks = class, xrange = range(x), yrange = range(y)))
ln
rr = relrisk(ln, sigma = 250)
plot(rr)
```